# AiM Documentary Studio — Blue/Green Cloud Build Pipeline
#
# Pure static SPA (nginx) — all AI calls go to the Flask middleware service.
#
# Deploys a new revision with 0% traffic, smoke-tests it via a tagged URL,
# then shifts 100% traffic. If smoke tests fail, production stays on the
# previous revision.
#
# Rollback (post-promotion):
#   gcloud run services update-traffic aim-documentary-studio \
#     --region=us-central1 --to-revisions=<previous-revision>=100
#
# The previous revision name is logged in the capture-current-revision step.
#
# Triggers on push to main via GitHub trigger. Set up the trigger with:
#
#   gcloud builds triggers create github \
#     --repo-name=aim-documentary-studio \
#     --repo-owner=grahamatarrowmedia \
#     --branch-pattern=^main$ \
#     --build-config=cloudbuild.yaml \
#     --region=global

substitutions:
  _REGION: us-central1
  _SERVICE_NAME: aim-documentary-studio
  _IMAGE: us-central1-docker.pkg.dev/gbr-aim-aiengine-prod/aim/documentary-studio
  _VITE_API_URL: ""
  _VITE_SUPABASE_URL: ""
  _VITE_SUPABASE_ANON_KEY: ""
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: ""
  _VITE_FIREBASE_PROJECT_ID: ""
  _VITE_ELEVENLABS_API_KEY: ""

steps:
  # Step 1: Build Docker image with frontend env vars as build args
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=VITE_API_URL=${_VITE_API_URL}
      - --build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}
      - --build-arg=VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}
      - --build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg=VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg=VITE_ELEVENLABS_API_KEY=${_VITE_ELEVENLABS_API_KEY}
      - -t
      - ${_IMAGE}:$COMMIT_SHA
      - -t
      - ${_IMAGE}:latest
      - .
    id: build

  # Step 2: Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}
    id: push
    waitFor:
      - build

  # Step 3: Capture current serving revision for rollback reference
  #         Also records whether the service exists (for first-deploy handling)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: capture-current-revision
    entrypoint: bash
    args:
      - '-c'
      - |
        if gcloud run services describe "${_SERVICE_NAME}" \
             --region=${_REGION} --format='value(status.traffic[0].revisionName)' > /workspace/previous-revision.txt 2>/dev/null; then
          echo "exists" > /workspace/service-exists.txt
          echo "=== Current serving revision: $(cat /workspace/previous-revision.txt) ==="
        else
          echo "none" > /workspace/previous-revision.txt
          echo "new" > /workspace/service-exists.txt
          echo "=== Service does not exist yet — first deploy ==="
        fi
    waitFor: ['-']

  # Step 4: Deploy new revision with 0% traffic (or full traffic on first deploy)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy-green
    entrypoint: bash
    args:
      - '-c'
      - |
        GREEN_FLAGS=""
        if [ "$(cat /workspace/service-exists.txt)" = "exists" ]; then
          GREEN_FLAGS="--no-traffic --tag=green"
        else
          echo "=== First deploy — skipping --no-traffic (not supported for new services) ==="
        fi

        gcloud run deploy "${_SERVICE_NAME}" \
          --image=${_IMAGE}:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --update-annotations=run.googleapis.com/invoker-iam-disabled=true \
          --memory=256Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          $${GREEN_FLAGS}
    waitFor:
      - push
      - capture-current-revision

  # Step 5: Smoke-test the green revision (or the live URL on first deploy)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: smoke-test
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "$(cat /workspace/service-exists.txt)" = "exists" ]; then
          # Get the green tag URL from the service description
          GREEN_URL=$(gcloud run services describe "${_SERVICE_NAME}" \
            --region=${_REGION} \
            --format='value(status.traffic.url)' | tr ',' '\n' | grep 'green---' | head -1)
        else
          # First deploy — no green tag, use the main service URL
          GREEN_URL=$(gcloud run services describe "${_SERVICE_NAME}" \
            --region=${_REGION} \
            --format='value(status.url)')
        fi

        if [ -z "$${GREEN_URL}" ]; then
          echo "ERROR: Could not find service URL"
          exit 1
        fi
        echo "=== Test URL: $${GREEN_URL} ==="

        # Test 1: GET / returns 200
        echo "=== Testing GET / ==="
        BODY=$(curl -s -w '\n%{http_code}' --max-time 30 "$${GREEN_URL}/")
        HTTP_CODE=$(echo "$${BODY}" | tail -1)
        CONTENT=$(echo "$${BODY}" | sed '$d')

        if [ "$${HTTP_CODE}" != "200" ]; then
          echo "FAIL: / returned $${HTTP_CODE} (expected 200)"
          exit 1
        fi
        echo "PASS: / returned 200"

        # Test 2: Response body contains id="root" (valid Vite build)
        echo "=== Checking for id=\"root\" in HTML ==="
        if echo "$${CONTENT}" | grep -q 'id="root"'; then
          echo "PASS: HTML contains id=\"root\""
        else
          echo "FAIL: HTML does not contain id=\"root\""
          echo "--- Response body (first 500 chars) ---"
          echo "$${CONTENT}" | head -c 500
          exit 1
        fi

        echo "=== All smoke tests passed ==="
    waitFor:
      - deploy-green

  # Step 6: Promote green revision to 100% traffic, then clean up tag
  #         (skipped on first deploy — already serving 100%)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: promote-green
    entrypoint: bash
    args:
      - '-c'
      - |
        if [ "$(cat /workspace/service-exists.txt)" != "exists" ]; then
          echo "=== First deploy — already serving 100% traffic, nothing to promote ==="
          exit 0
        fi

        echo "=== Promoting green revision to 100% traffic ==="
        gcloud run services update-traffic "${_SERVICE_NAME}" \
          --region=${_REGION} \
          --to-latest

        echo "=== Removing green tag ==="
        gcloud run services update-traffic "${_SERVICE_NAME}" \
          --region=${_REGION} \
          --remove-tags=green

        echo "=== Previous revision (for rollback): $(cat /workspace/previous-revision.txt) ==="
        echo "=== Deployment complete ==="
    waitFor:
      - smoke-test

images:
  - ${_IMAGE}:$COMMIT_SHA
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
