# AiM Documentary Studio — Cloud Build CI/CD Pipeline
#
# Triggers on push to main via GitHub trigger. Set up the trigger with:
#
#   gcloud builds triggers create github \
#     --repo-name=aim-documentary-studio \
#     --repo-owner=grahamatarrowmedia \
#     --branch-pattern=^main$ \
#     --build-config=cloudbuild.yaml \
#     --region=europe-west1
#
# Required Secret Manager secrets (create before first build):
#   VITE_SUPABASE_URL, VITE_SUPABASE_ANON_KEY, VITE_FIREBASE_API_KEY,
#   VITE_FIREBASE_AUTH_DOMAIN, VITE_FIREBASE_PROJECT_ID, VITE_ELEVENLABS_API_KEY,
#   GEMINI_API_KEY

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: aim-documentary-studio
  _IMAGE: europe-west1-docker.pkg.dev/fremantle-ai-studio-prod/aim/documentary-studio

availableSecrets:
  secretManager:
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_SUPABASE_URL/versions/latest
      env: VITE_SUPABASE_URL
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_SUPABASE_ANON_KEY/versions/latest
      env: VITE_SUPABASE_ANON_KEY
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_FIREBASE_API_KEY/versions/latest
      env: VITE_FIREBASE_API_KEY
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_FIREBASE_AUTH_DOMAIN/versions/latest
      env: VITE_FIREBASE_AUTH_DOMAIN
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_FIREBASE_PROJECT_ID/versions/latest
      env: VITE_FIREBASE_PROJECT_ID
    - versionName: projects/fremantle-ai-studio-prod/secrets/VITE_ELEVENLABS_API_KEY/versions/latest
      env: VITE_ELEVENLABS_API_KEY
    - versionName: projects/fremantle-ai-studio-prod/secrets/GEMINI_API_KEY/versions/latest
      env: GEMINI_API_KEY

steps:
  # Step 1: Build Docker image with frontend env vars as build args
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg VITE_SUPABASE_URL=$$VITE_SUPABASE_URL \
          --build-arg VITE_SUPABASE_ANON_KEY=$$VITE_SUPABASE_ANON_KEY \
          --build-arg VITE_FIREBASE_API_KEY=$$VITE_FIREBASE_API_KEY \
          --build-arg VITE_FIREBASE_AUTH_DOMAIN=$$VITE_FIREBASE_AUTH_DOMAIN \
          --build-arg VITE_FIREBASE_PROJECT_ID=$$VITE_FIREBASE_PROJECT_ID \
          --build-arg VITE_ELEVENLABS_API_KEY=$$VITE_ELEVENLABS_API_KEY \
          --build-arg GEMINI_API_KEY=$$GEMINI_API_KEY \
          -t ${_IMAGE}:$COMMIT_SHA \
          -t ${_IMAGE}:latest \
          .
    secretEnv:
      - VITE_SUPABASE_URL
      - VITE_SUPABASE_ANON_KEY
      - VITE_FIREBASE_API_KEY
      - VITE_FIREBASE_AUTH_DOMAIN
      - VITE_FIREBASE_PROJECT_ID
      - VITE_ELEVENLABS_API_KEY
      - GEMINI_API_KEY
    id: build

  # Step 2: Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}
    id: push
    waitFor:
      - build

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=10
      - --set-env-vars=GCP_PROJECT_ID=fremantle-ai-studio-prod,GCP_LOCATION=europe-west1
    id: deploy
    waitFor:
      - push

images:
  - ${_IMAGE}:$COMMIT_SHA
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
