# AiM Documentary Studio — Cloud Build CI/CD Pipeline
#
# Triggers on push to main via GitHub trigger. Set up the trigger with:
#
#   gcloud builds triggers create github \
#     --repo-name=aim-documentary-studio \
#     --repo-owner=grahamatarrowmedia \
#     --branch-pattern=^main$ \
#     --build-config=cloudbuild.yaml \
#     --region=global
#
# Optional: To pass secrets as build-time substitutions, update the trigger:
#
#   gcloud builds triggers update aim-documentary-studio --region=global \
#     --update-substitutions=_VITE_SUPABASE_URL=...,_VITE_FIREBASE_API_KEY=...
#
# Or create them in Secret Manager and reference via --secret-config.

substitutions:
  _REGION: europe-west1
  _SERVICE_NAME: aim-documentary-studio
  _IMAGE: europe-west1-docker.pkg.dev/gbr-aim-aiengine-prod/aim/documentary-studio
  _VITE_SUPABASE_URL: ""
  _VITE_SUPABASE_ANON_KEY: ""
  _VITE_FIREBASE_API_KEY: ""
  _VITE_FIREBASE_AUTH_DOMAIN: ""
  _VITE_FIREBASE_PROJECT_ID: ""
  _VITE_ELEVENLABS_API_KEY: ""
  _GEMINI_API_KEY: ""

steps:
  # Step 1: Build Docker image with frontend env vars as build args
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg=VITE_SUPABASE_URL=${_VITE_SUPABASE_URL}
      - --build-arg=VITE_SUPABASE_ANON_KEY=${_VITE_SUPABASE_ANON_KEY}
      - --build-arg=VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}
      - --build-arg=VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}
      - --build-arg=VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}
      - --build-arg=VITE_ELEVENLABS_API_KEY=${_VITE_ELEVENLABS_API_KEY}
      - --build-arg=GEMINI_API_KEY=${_GEMINI_API_KEY}
      - -t
      - ${_IMAGE}:$COMMIT_SHA
      - -t
      - ${_IMAGE}:latest
      - .
    id: build

  # Step 2: Push image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}
    id: push
    waitFor:
      - build

  # Step 3: Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --image=${_IMAGE}:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=10
      - --set-env-vars=GCP_PROJECT_ID=gbr-aim-aiengine-prod,GCP_LOCATION=europe-west1
    id: deploy
    waitFor:
      - push

images:
  - ${_IMAGE}:$COMMIT_SHA
  - ${_IMAGE}:latest

options:
  logging: CLOUD_LOGGING_ONLY
